### PR TITLE
fix: folder structure

### PR DESCRIPTION
**Pull request by shashankp10**
# Description 
- Fixed the folder structure of the project
closes https://github.com/shashankp10/Navify/issues/1

### CODE REVIEW

**Review by tejaskh3 — CHANGES_REQUESTED** [review]
Can you please add description?

**Comment by tejaskh3** [comment]
> Can you please add description?

Okay

**Comment by shashankp10** [comment]
okay

**Review by tejaskh3 — APPROVED** [review]
LGTM

**Pull request merged**
